# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # change the cluster name to yours
  name: mycluster-dev-cluster
  region: eu-west-1
  tags:
    #change the owners
    owner_email: owner@mail.com
    owner: "Owner name"
    purpose: dev

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"

# if you prefer to use a created subnet/vpc and do not create one for your eks
vpc:
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      eu-west-1a:
        id: "subnet-xxxx"
      eu-west-1b:
        id: "subnet-yyyy"
      eu-west-1c:
        id: "subnet-zzzz"
